<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: redis.proto

namespace Neptune;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>neptune.DoResponse</code>
 */
class DoResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bytes Response = 1;</code>
     */
    private $Response = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $Response
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Redis::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bytes Response = 1;</code>
     * @return string
     */
    public function getResponse()
    {
        return $this->Response;
    }

    /**
     * Generated from protobuf field <code>bytes Response = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setResponse($var)
    {
        GPBUtil::checkString($var, False);
        $this->Response = $var;

        return $this;
    }

}

