<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: redis.proto

namespace Neptune;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>neptune.DoReleaseRequest</code>
 */
class DoReleaseRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string RegistId = 1;</code>
     */
    private $RegistId = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $RegistId
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Redis::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string RegistId = 1;</code>
     * @return string
     */
    public function getRegistId()
    {
        return $this->RegistId;
    }

    /**
     * Generated from protobuf field <code>string RegistId = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setRegistId($var)
    {
        GPBUtil::checkString($var, True);
        $this->RegistId = $var;

        return $this;
    }

}

