<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: redis.proto

namespace Neptune;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>neptune.DoRequest</code>
 */
class DoRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string RegistId = 1;</code>
     */
    private $RegistId = '';
    /**
     * Generated from protobuf field <code>string Name = 2;</code>
     */
    private $Name = '';
    /**
     * Generated from protobuf field <code>bytes Params = 3;</code>
     */
    private $Params = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $RegistId
     *     @type string $Name
     *     @type string $Params
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Redis::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string RegistId = 1;</code>
     * @return string
     */
    public function getRegistId()
    {
        return $this->RegistId;
    }

    /**
     * Generated from protobuf field <code>string RegistId = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setRegistId($var)
    {
        GPBUtil::checkString($var, True);
        $this->RegistId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string Name = 2;</code>
     * @return string
     */
    public function getName()
    {
        return $this->Name;
    }

    /**
     * Generated from protobuf field <code>string Name = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->Name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes Params = 3;</code>
     * @return string
     */
    public function getParams()
    {
        return $this->Params;
    }

    /**
     * Generated from protobuf field <code>bytes Params = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setParams($var)
    {
        GPBUtil::checkString($var, False);
        $this->Params = $var;

        return $this;
    }

}

